# Generated by Django 5.2.15 on 2026-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__main__', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
