# Generated by Django 5.2.15 on 2026-07-02 12:00

from django.db import migrations, models


def default_severities():
    return ['ALTA', 'CRITICA']


class Migration(migrations.Migration):

    dependencies = [
        ('__main__', '0003_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_severities',
            field=models.JSONField(default=default_severities),
        ),
    ]