# Generated by Django 5.2.15 on 2026-09-18 16:12

import __main__
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__main__', '0004_userprofile_telegram_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_severities',
            field=models.JSONField(default=__main__.default_telegram_severities),
        ),
    ]
