# Generated by Django 5.2.15 on 2026-09-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('__main__', '0005_agent_metrics'),
        ('__main__', '0005_alter_userprofile_telegram_chat_id_and_more'),
    ]

    operations = [
    ]
