# Generated by AgentSOC for CTI, IOC, Security Policies, and Sessions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('__main__', '0006_merge_20260921_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOCIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.CharField(db_index=True, max_length=191, unique=True)),
                ('indicator_type', models.CharField(choices=[('ip', 'Dirección IP'), ('domain', 'Nombre de Dominio'), ('hash_md5', 'Hash MD5'), ('hash_sha256', 'Hash SHA256'), ('url', 'URL Maliciosa')], db_index=True, default='ip', max_length=20)),
                ('threat_type', models.CharField(choices=[('c2_botnet', 'C2 / Servidor de Comando y Control'), ('malware', 'Distribución de Malware'), ('ransomware', 'Ransomware / Extorsión'), ('phishing', 'Phishing / Robo de Credenciales'), ('scanner', 'Escáner / Explotación de Vulnerabilidades'), ('tor_exit', 'Nodo de Salida Tor'), ('brute_force', 'Ataque de Fuerza Bruta / Credential Stuffing')], db_index=True, default='c2_botnet', max_length=50)),
                ('malware_family', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source', models.CharField(default='Feodo Tracker (abuse.ch)', max_length=100)),
                ('confidence', models.IntegerField(default=85)),
                ('severity', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='CRITICA', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ioc_indicators',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TorExitNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=50, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tor_exit_nodes',
            },
        ),
        migrations.CreateModel(
            name='IPGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=50, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('isp', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ip_geolocations',
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_mfa_admin', models.BooleanField(default=True)),
                ('enforce_mfa_all', models.BooleanField(default=False)),
                ('max_active_sessions_per_user', models.IntegerField(default=5)),
                ('session_timeout_hours', models.IntegerField(default=24)),
                ('alert_on_new_device', models.BooleanField(default=True)),
                ('alert_on_new_ip', models.BooleanField(default=True)),
                ('notify_suspicious_email', models.BooleanField(default=True)),
                ('notify_suspicious_telegram', models.BooleanField(default=True)),
                ('detect_impossible_travel', models.BooleanField(default=True)),
                ('impossible_travel_speed_kmh', models.IntegerField(default=800)),
                ('detect_tor_exit_nodes', models.BooleanField(default=True)),
                ('block_tor_logins', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'security_policies',
            },
        ),
        migrations.CreateModel(
            name='SystemLatencyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('icmp_latency_ms', models.FloatField(blank=True, null=True)),
                ('http_latency_ms', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_latency_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('device_name', models.CharField(default='Dispositivo desconocido', max_length=150)),
                ('device_type', models.CharField(default='desktop', max_length=50)),
                ('location', models.CharField(default='Red Interna / Local', max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('is_tor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='TrustedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('device_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.CharField(blank=True, default='Autorizado como legítimo', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_accesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IOCHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.CharField(db_index=True, max_length=191)),
                ('indicator_type', models.CharField(default='ip', max_length=20)),
                ('threat_type', models.CharField(default='c2_botnet', max_length=50)),
                ('malware_family', models.CharField(blank=True, default='', max_length=100)),
                ('source_feed', models.CharField(blank=True, default='', max_length=100)),
                ('severity', models.CharField(default='CRITICA', max_length=20)),
                ('source_event', models.CharField(default='Desconocido', max_length=255)),
                ('matched_value', models.CharField(max_length=191)),
                ('client_ip', models.CharField(blank=True, default='', max_length=50)),
                ('action_taken', models.CharField(default='Alerta SOC Generada', max_length=150)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ioc_hits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ioc_hits',
                'ordering': ['-created_at'],
            },
        ),
    ]
